name: Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  semgrep:
    name: "SAST - Semgrep"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep \
            --config=p/owasp-top-ten \
            --config=p/python \
            --config=p/secrets \
            --config=p/flask \
            --config=p/sql-injection \
            --config=p/command-injection \
            --verbose \
            --error \
            .
