name: Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  semgrep:
    name: "SAST - Semgrep"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config=p/owasp-top-ten \
                  --config=p/python \
                  --config=p/secrets \
                  .

  gitleaks:
    name: "Secret Scan - GitLeaks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run GitLeaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.0_linux_x64.tar.gz
          ./gitleaks detect --source . --verbose

  sca:
    name: "SCA - pip-audit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

  trivy:
    name: "Container Scan - Trivy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t devsecops-lab:latest .
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-lab:latest
          format: table
          severity: CRITICAL,HIGH
          exit-code: '1'
      - name: Generate SBOM
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-lab:latest
          format: cyclonedx
          output: sbom.json
      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

